services:
  - mysql

env:
  - MYSQL_HOST=localhost
  - MYSQL_DATABASE=travis_db
  - MYSQL_USERNAME=root
  - MYSQL_PASSWORD=

language: node_js

node_js:
  - 'node'
  - '11'
  - '12'

branches:
  only:
  - /.*/

before_install:
  - mysql -e 'CREATE DATABASE travis_db;'

install:
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1

script:
  - git clone https://github.com/AnyhowStep/tsql.git
  - cd tsql
  - npm install
  - npm run build
  - cd ../
  - npm link ./tsql
  - npm run sanity-check-travis
  # - npm install codecov

after_success:
  # - ./node_modules/.bin/c8 report --reporter=text-lcov | ./node_modules/.bin/codecov --pipe
